#include <stdio.h>
#include "bsvt_id.h"
main () {
	int i;
	i = T0_1; /* C_0 - р0_1 */
	i = ODNA_SYEKUNDA; /* C_1 - ндмю_яейсмдю */
	i = DVYE_SYEKUNDY; /* C_2 - дбе_яейсмдш */
	i = TRI_SYEKUNDY; /* C_3 - рпх_яейсмдш */
	i = PYAT__SYEKUND; /* C_4 - оърэ_яейсмд */
	i = DYESYAT__SYEKUND; /* C_5 - деяърэ_яейсмд */
	i = DVADTSAT__SYEKUND; /* C_6 - дбюджюрэ_яейсмд */
	i = TAJMAUT_NA_SRABATYVANIYE_ZAT_VAK; /* C_7 - рюилюср_мю_япюаюршбюмхе_гюр_бюй */
	i = TAJMAUT_NA_SRABATYVANIYE_SAPUNA; /* C_8 - рюилюср_мю_япюаюршбюмхе_яюосмю */
	i = TAJMAUT_NA_SRABATYVANIYE_USTR_PLAV_PUSKA; /* C_9 - рюилюср_мю_япюаюршбюмхе_сярп_окюб_осяйю */
	i = TAJMAUT_NA_SRABATYVANIYE_VAK_NASOSA; /* C_10 - рюилюср_мю_япюаюршбюмхе_бюй_мюяняю */
	i = TAJMAUT_NA_SRABATYVANIYE_VYENTILYATORA; /* C_11 - рюилюср_мю_япюаюршбюмхе_бемрхкърнпю */
	i = TAJMAUT_NA_SRABATYVANIYE_RYEG_T; /* C_12 - рюилюср_мю_япюаюршбюмхе_пец_р */
	i = TAJMAUT_NA_SRABATYVANIYE_RYEG_UR; /* C_13 - рюилюср_мю_япюаюршбюмхе_пец_сп */
	i = TAJMAUT_NA_SRABATYVANIYE_NASOS_OKHL; /* C_14 - рюилюср_мю_япюаюршбюмхе_мюяня_нук */
	i = TAJMAUT_NA_SVYAZ__S_GUI; /* C_15 - рюилюср_мю_ябъгэ_я_цсх */
	i = ODNA_MINUTA; /* C_16 - ндмю_лхмсрю */
	i = DVYE_MINUTY; /* C_17 - дбе_лхмсрш */
	i = PYAT__MINUT; /* C_18 - оърэ_лхмср */
	i = TRIDTSAT__MINUT; /* C_19 - рпхджюрэ_лхмср */
	i = TAJMAUT_ZADYERZHKA_NA_OTKACHKU; /* C_20 - рюилюср_гюдепфйю_мю_нрйювйс */
	i = VKL; /* C_21 - бйк */
	i = VYK; /* C_22 - бшй */
	i = OTKR; /* C_23 - нрйп */
	i = ZAKR; /* C_24 - гюйп */
	i = YEST_; /* C_25 - еярэ */
	i = NYET; /* C_26 - мер */
	i = NORMA; /* C_27 - мнплю */
	i = VNYE_NORMY; /* C_28 - бме_мнплш */
	i = TAJMAUT_NA_DIAGNOSTIKU_RAZRYVA_SVYAZI; /* C_29 - рюилюср_мю_дхюцмнярхйс_пюгпшбю_ябъгх */
	i = T_Pryedyel_nayaVbakyeOkhlazhdyeniya; /* C_30 - р_оПЕДЕКЭМЮЪбАЮЙЕнУКЮФДЕМХЪ */
	i = ZD_P_VbakyeKompryessora; /* C_31 - гд_P_бАЮЙЕйНЛОПЕЯЯНПЮ */
	i = T_GISTYERYEZIS_VODY_V_BAKYE; /* C_32 - р_цхярепегхя_бндш_б_аюйе */
	i = T_GISTYERYEZIS_VODY_V_RUBAKHYE; /* C_33 - р_цхярепегхя_бндш_б_псаюуе */
	i = UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_NIZKIJ; /* спнбемэ_бндш_б_аюйе_нукюфдемхъ_мхгйхи */
	i = UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_VYSOKIJ; /* спнбемэ_бндш_б_аюйе_нукюфдемхъ_бшянйхи */
	i = UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_V_NORMYE; /* спнбемэ_бндш_б_аюйе_нукюфдемхъ_б_мнпле */
	i = TYEMPYERATURA_VODY_V_BAKYE_OKHLAZHDYENIYA_NIZKAYA; /* релоепюрспю_бндш_б_аюйе_нукюфдемхъ_мхгйюъ */
	i = TYEMPYERATURA_VODY_V_BAKYE_OKHLAZHDYENIYA_VYSOKAYA; /* релоепюрспю_бндш_б_аюйе_нукюфдемхъ_бшянйюъ */
	i = TYEMPYERATURA_VODY_V_BAKYE_OKHLAZHDYENIYA_V_NORMYE; /* релоепюрспю_бндш_б_аюйе_нукюфдемхъ_б_мнпле */
	i = TYEMPYERATURA_VODY_V_RUBASHKYE_OKHLAZHDYENIYA_NIZKAYA; /* релоепюрспю_бндш_б_псаюьйе_нукюфдемхъ_мхгйюъ */
	i = TYEMPYERATURA_VODY_V_RUBASHKYE_OKHLAZHDYENIYA_VYSOKAYA; /* релоепюрспю_бндш_б_псаюьйе_нукюфдемхъ_бшянйюъ */
	i = TYEMPYERATURA_VODY_V_RUBASHKYE_OKHLAZHDYENIYA_V_NORMYE; /* релоепюрспю_бндш_б_псаюьйе_нукюфдемхъ_б_мнпле */
	i = DAVLYENIYE_V_VAKUUMNOJ_TRUBYE_V_NORMYE; /* дюбкемхе_б_бюйсслмни_рпсае_б_мнпле */
	i = DAVLYENIYE_V_VAKUUMNOJ_TRUBYE_VNYE_NORMY; /* дюбкемхе_б_бюйсслмни_рпсае_бме_мнплш */
	i = SKOROST__OTKACHKI_V_NORMYE; /* яйнпнярэ_нрйювйх_б_мнпле */
	i = SKOROST__OTKACHKI_NIZHYE_NORMY; /* яйнпнярэ_нрйювйх_мхфе_мнплш */
	i = DAVLYENIYE_V_BAKYE_KOMPRYESSORA_V_NORMYE; /* дюбкемхе_б_аюйе_йнлопеяянпю_б_мнпле */
	i = DAVLYENIYE_V_BAKYE_KOMPRYESSORA_NIZHYE_NORMY; /* дюбкемхе_б_аюйе_йнлопеяянпю_мхфе_мнплш */
	i = OTKR_ZATVOR_VAK; /* нрйп_гюрбнп_бюй */
	i = ZAKR_ZATVOR_VAK; /* гюйп_гюрбнп_бюй */
	i = OTKR_SAPUN; /* нрйп_яюосм */
	i = ZAKR_SAPUN; /* гюйп_яюосм */
	i = VKL_USTR_PLAV_PUSKA; /* бйк_сярп_окюб_осяйю */
	i = VYK_USTR_PLAV_PUSKA; /* бшй_сярп_окюб_осяйю */
	i = VKL_PIT_VAK_NASOSA; /* бйк_охр_бюй_мюяняю */
	i = VYK_PIT_VAK_NASOSA; /* бшй_охр_бюй_мюяняю */
	i = VKL_PIT_VYENTILYATOR; /* бйк_охр_бемрхкърнп */
	i = VYK_PIT_VYENTILYATOR; /* бшй_охр_бемрхкърнп */
	i = VKL_PIT_RYEG_T; /* бйк_охр_пец_р */
	i = VYK_PIT_RYEG_T; /* бшй_охр_пец_р */
	i = VKL_PIT_RYEG_UR; /* бйк_охр_пец_сп */
	i = VYK_PIT_RYEG_UR; /* бшй_охр_пец_сп */
	i = VKL_PIT_NAS_OKHL; /* бйк_охр_мюя_нук */
	i = VYK_PIT_NAS_OKHL; /* бшй_охр_мюя_нук */
	i = VKL_VAKUUMIROVANIYE_TRUBY; /* бйк_бюйсслхпнбюмхе_рпсаш */
	i = VYK_VAKUUMIROVANIYE_TRUBY; /* бшй_бюйсслхпнбюмхе_рпсаш */
	i = VKL_NASOS_VAKUUMNYJ; /* бйк_мюяня_бюйсслмши */
	i = VYK_NASOS_VAKUUMNYJ; /* бшй_мюяня_бюйсслмши */
	i = KOMANDY_OT_GUI; /* йнлюмдш_нр_цсх */
	i = IZMN_FP_P_VbakyeKompryessora; /* хглм_то_P_бАЮЙЕйНЛОПЕЯЯНПЮ */
	i = IZMN_FP_P_Vpatrubkye; /* хглм_то_P_бОЮРПСАЙЕ */
	i = IZMN_FP_T_Vrubashkye; /* хглм_то_T_бПСАЮЬЙЕ */
	i = IZMN_FP_T_Vbakye; /* хглм_то_T_бАЮЙЕ */
	i = IZMN_FP_P_VtrubyeSidyer; /* хглм_то_P_бРПСАЕяХДЕП */
	i = KOMANDY_IZM_FP; /* йнлюмдш_хгл_то */
	i = PK_GUI_OTKAZ_OTKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_нрйюг_нрйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_OTKAZ_ZAKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_нрйюг_гюйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_OTKAZ_OTKRYTIYA_SAPUNA; /* ой_цсх_нрйюг_нрйпшрхъ_яюосмю */
	i = PK_GUI_OTKAZ_ZAKRYTIYA_SAPUNA; /* ой_цсх_нрйюг_гюйпшрхъ_яюосмю */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_VYENTILYATORA; /* ой_цсх_нрйюг_бйкчвемхъ_бемрхкърнпю */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_VYENTILYATORA; /* ой_цсх_нрйюг_бшйкчвемхъ_бемрхкърнпю */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_USTR_PLAV_PUSKA; /* ой_цсх_нрйюг_бйкчвемхъ_сярп_окюб_осяйю */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_USTR_PLAV_PUSKA; /* ой_цсх_нрйюг_бшйкчвемхъ_сярп_окюб_осяйю */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_RYEGULYATORA_TYEMPYERATURY; /* ой_цсх_нрйюг_бйкчвемхъ_пецскърнпю_релоепюрспш */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_RYEGULYATORA_TYEMPYERATURY; /* ой_цсх_нрйюг_бшйкчвемхъ_пецскърнпю_релоепюрспш */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_RYEGULYATORA_UROVNYA; /* ой_цсх_нрйюг_бйкчвемхъ_пецскърнпю_спнбмъ */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_RYEGULYATORA_UROVNYA; /* ой_цсх_нрйюг_бшйкчвемхъ_пецскърнпю_спнбмъ */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_NASOSA_OKHLAZHDYENIYA; /* ой_цсх_нрйюг_бйкчвемхъ_мюяняю_нукюфдемхъ */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_NASOSA_OKHLAZHDYENIYA; /* ой_цсх_нрйюг_бшйкчвемхъ_мюяняю_нукюфдемхъ */
	i = PK_GUI_IDYET_VAKUUMIROVANIYE_OTKAZ_VYPOLNYENIYA_KOMANDY; /* ой_цсх_хдер_бюйсслхпнбюмхе_нрйюг_бшонкмемхъ_йнлюмдш */
	i = PK_GUI_NYET_USLOVIJ_DLYA_VYPOLNYENIYA_KOMANDY; /* ой_цсх_мер_сякнбхи_дкъ_бшонкмемхъ_йнлюмдш */
	i = PK_GUI_UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_VNYE_NORMY_OTKAZ_VYPOLNYENI; /* ой_цсх_спнбемэ_бндш_б_аюйе_нукюфдемхъ_бме_мнплш_нрйюг_бшонкмемх */
	i = PK_GUI_OTRITSATYEL_NAYA_TYEMPYERATURA_VODY_OTKAZ_VYPOLNYENIYA_KOMANDY; /* ой_цсх_нрпхжюрекэмюъ_релоепюрспю_бндш_нрйюг_бшонкмемхъ_йнлюмдш */
	i = PK_GUI_DAVLYENIYE_V_PATRUBKYE_NYE_UMYEN_SHAYETSYA; /* ой_цсх_дюбкемхе_б_оюрпсайе_ме_слемэьюеряъ */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_PITANIYA_VAKUUMNOGO_NASOSA; /* ой_цсх_нрйюг_бйкчвемхъ_охрюмхъ_бюйсслмнцн_мюяняю */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_PITANIYA_VAKUUMNOGO_NASOSA; /* ой_цсх_нрйюг_бшйкчвемхъ_охрюмхъ_бюйсслмнцн_мюяняю */
	i = PK_GUI_FP_P_VbakyeKompryessora; /* ой_цсх_то_P_бАЮЙЕйНЛОПЕЯЯНПЮ */
	i = PK_GUI_FP_P_Vpatrubkye; /* ой_цсх_то_P_бОЮРПСАЙЕ */
	i = PK_GUI_FP_T_Vrubashkye; /* ой_цсх_то_T_бПСАЮЬЙЕ */
	i = PK_GUI_FP_T_Vbakye; /* ой_цсх_то_T_бАЮЙЕ */
	i = PK_GUI_FP_P_VtrubyeSidyer; /* ой_цсх_то_P_бРПСАЕяХДЕП */
	i = PK_GUI_OSHIBKA_KODA_KOMANDY_OT_GUI; /* ой_цсх_ньхайю_йндю_йнлюмдш_нр_цсх */
	fclose(file);
}
