#include <stdio.h>
#include "bsvt_id.h"
main () {
	int i;
	i = T0_1; /* C_0 - р0_1 */
	i = ODNA_SYEKUNDA; /* C_1 - ндмю_яейсмдю */
	i = DVYE_SYEKUNDY; /* C_2 - дбе_яейсмдш */
	i = TRI_SYEKUNDY; /* C_3 - рпх_яейсмдш */
	i = PYAT__SYEKUND; /* C_4 - оърэ_яейсмд */
	i = DYESYAT__SYEKUND; /* C_5 - деяърэ_яейсмд */
	i = DVADTSAT__SYEKUND; /* C_6 - дбюджюрэ_яейсмд */
	i = TAJMAUT_NA_SRABATYVANIYE_ZAT_VAK; /* C_7 - рюилюср_мю_япюаюршбюмхе_гюр_бюй */
	i = TAJMAUT_NA_SRABATYVANIYE_SAPUNA; /* C_8 - рюилюср_мю_япюаюршбюмхе_яюосмю */
	i = TAJMAUT_NA_SRABATYVANIYE_USTR_PLAV_PUSKA; /* C_9 - рюилюср_мю_япюаюршбюмхе_сярп_окюб_осяйю */
	i = TAJMAUT_NA_SRABATYVANIYE_VAK_NASOSA; /* C_10 - рюилюср_мю_япюаюршбюмхе_бюй_мюяняю */
	i = TAJMAUT_NA_SRABATYVANIYE_VYENTILYATORA; /* C_11 - рюилюср_мю_япюаюршбюмхе_бемрхкърнпю */
	i = TAJMAUT_NA_SRABATYVANIYE_RYEG_T; /* C_12 - рюилюср_мю_япюаюршбюмхе_пец_р */
	i = TAJMAUT_NA_SRABATYVANIYE_RYEG_UR; /* C_13 - рюилюср_мю_япюаюршбюмхе_пец_сп */
	i = TAJMAUT_NA_SRABATYVANIYE_NASOS_OKHL; /* C_14 - рюилюср_мю_япюаюршбюмхе_мюяня_нук */
	i = TAJMAUT_NA_SVYAZ__S_GUI; /* C_15 - рюилюср_мю_ябъгэ_я_цсх */
	i = ODNA_MINUTA; /* C_16 - ндмю_лхмсрю */
	i = DVYE_MINUTY; /* C_17 - дбе_лхмсрш */
	i = PYAT__MINUT; /* C_18 - оърэ_лхмср */
	i = TRIDTSAT__MINUT; /* C_19 - рпхджюрэ_лхмср */
	i = TAJMAUT_ZADYERZHKA_NA_OTKACHKU; /* C_20 - рюилюср_гюдепфйю_мю_нрйювйс */
	i = VKL; /* C_21 - бйк */
	i = VYK; /* C_22 - бшй */
	i = OTKR; /* C_23 - нрйп */
	i = ZAKR; /* C_24 - гюйп */
	i = YEST_; /* C_25 - еярэ */
	i = NYET; /* C_26 - мер */
	i = NORMA; /* C_27 - мнплю */
	i = VNYE_NORMY; /* C_28 - бме_мнплш */
	i = DOSTOVYERNO; /* C_29 - днярнбепмн */
	i = NYEDOSTOVYERNO; /* C_30 - меднярнбепмн */
	i = TAJMAUT_NA_DIAGNOSTIKU_RAZRYVA_SVYAZI; /* C_31 - рюилюср_мю_дхюцмнярхйс_пюгпшбю_ябъгх */
	i = T_Pryedyel_nayaVbakyeOkhlazhdyeniya; /* C_32 - р_оПЕДЕКЭМЮЪбАЮЙЕнУКЮФДЕМХЪ */
	i = T_GISTYERYEZIS_VODY_V_BAKYE; /* C_33 - р_цхярепегхя_бндш_б_аюйе */
	i = T_GISTYERYEZIS_VODY_V_RUBAKHYE; /* C_34 - р_цхярепегхя_бндш_б_псаюуе */
	i = PK_GUI_UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_NIZKIJ; /* ой_цсх_спнбемэ_бндш_б_аюйе_нукюфдемхъ_мхгйхи */
	i = PK_GUI_UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_VYSOKIJ; /* ой_цсх_спнбемэ_бндш_б_аюйе_нукюфдемхъ_бшянйхи */
	i = PK_GUI_UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_V_NORMYE; /* ой_цсх_спнбемэ_бндш_б_аюйе_нукюфдемхъ_б_мнпле */
	i = PK_GUI_TYEMPYERATURA_VODY_V_BAKYE_OKHLAZHDYENIYA_NIZKAYA; /* ой_цсх_релоепюрспю_бндш_б_аюйе_нукюфдемхъ_мхгйюъ */
	i = PK_GUI_TYEMPYERATURA_VODY_V_BAKYE_OKHLAZHDYENIYA_VYSOKAYA; /* ой_цсх_релоепюрспю_бндш_б_аюйе_нукюфдемхъ_бшянйюъ */
	i = PK_GUI_TYEMPYERATURA_VODY_V_BAKYE_OKHLAZHDYENIYA_V_NORMYE; /* ой_цсх_релоепюрспю_бндш_б_аюйе_нукюфдемхъ_б_мнпле */
	i = PK_GUI_TYEMPYERATURA_VODY_V_RUBASHKYE_OKHLAZHDYENIYA_NIZKAYA; /* ой_цсх_релоепюрспю_бндш_б_псаюьйе_нукюфдемхъ_мхгйюъ */
	i = PK_GUI_TYEMPYERATURA_VODY_V_RUBASHKYE_OKHLAZHDYENIYA_VYSOKAYA; /* ой_цсх_релоепюрспю_бндш_б_псаюьйе_нукюфдемхъ_бшянйюъ */
	i = PK_GUI_TYEMPYERATURA_VODY_V_RUBASHKYE_OKHLAZHDYENIYA_V_NORMYE; /* ой_цсх_релоепюрспю_бндш_б_псаюьйе_нукюфдемхъ_б_мнпле */
	i = PK_GUI_DAVLYENIYE_V_VAKUUMNOJ_TRUBYE_V_NORMYE; /* ой_цсх_дюбкемхе_б_бюйсслмни_рпсае_б_мнпле */
	i = PK_GUI_DAVLYENIYE_V_VAKUUMNOJ_TRUBYE_VNYE_NORMY; /* ой_цсх_дюбкемхе_б_бюйсслмни_рпсае_бме_мнплш */
	i = PK_GUI_SKOROST__OTKACHKI_V_NORMYE; /* ой_цсх_яйнпнярэ_нрйювйх_б_мнпле */
	i = PK_GUI_SKOROST__OTKACHKI_NIZHYE_NORMY; /* ой_цсх_яйнпнярэ_нрйювйх_мхфе_мнплш */
	i = PK_GUI_DAVLYENIYE_V_BAKYE_KOMPRYESSORA_V_NORMYE; /* ой_цсх_дюбкемхе_б_аюйе_йнлопеяянпю_б_мнпле */
	i = PK_GUI_DAVLYENIYE_V_BAKYE_KOMPRYESSORA_NIZHYE_NORMY; /* ой_цсх_дюбкемхе_б_аюйе_йнлопеяянпю_мхфе_мнплш */
	i = KOM_GUI_OTKR_ZATVOR_VAK; /* йнл_цсх_нрйп_гюрбнп_бюй */
	i = KOM_GUI_ZAKR_ZATVOR_VAK; /* йнл_цсх_гюйп_гюрбнп_бюй */
	i = KOM_GUI_OTKR_SAPUN; /* йнл_цсх_нрйп_яюосм */
	i = KOM_GUI_ZAKR_SAPUN; /* йнл_цсх_гюйп_яюосм */
	i = KOM_GUI_VKL_USTR_PLAV_PUSKA; /* йнл_цсх_бйк_сярп_окюб_осяйю */
	i = KOM_GUI_VYK_USTR_PLAV_PUSKA; /* йнл_цсх_бшй_сярп_окюб_осяйю */
	i = KOM_GUI_VKL_PIT_VAK_NASOSA; /* йнл_цсх_бйк_охр_бюй_мюяняю */
	i = KOM_GUI_VYK_PIT_VAK_NASOSA; /* йнл_цсх_бшй_охр_бюй_мюяняю */
	i = KOM_GUI_VKL_PIT_VYENTILYATOR; /* йнл_цсх_бйк_охр_бемрхкърнп */
	i = KOM_GUI_VYK_PIT_VYENTILYATOR; /* йнл_цсх_бшй_охр_бемрхкърнп */
	i = KOM_GUI_VKL_PIT_RYEG_T; /* йнл_цсх_бйк_охр_пец_р */
	i = KOM_GUI_VYK_PIT_RYEG_T; /* йнл_цсх_бшй_охр_пец_р */
	i = KOM_GUI_VKL_PIT_RYEG_UR; /* йнл_цсх_бйк_охр_пец_сп */
	i = KOM_GUI_VYK_PIT_RYEG_UR; /* йнл_цсх_бшй_охр_пец_сп */
	i = KOM_GUI_VKL_PIT_NAS_OKHL; /* йнл_цсх_бйк_охр_мюя_нук */
	i = KOM_GUI_VYK_PIT_NAS_OKHL; /* йнл_цсх_бшй_охр_мюя_нук */
	i = KOM_GUI_VKL_VAKUUMIROVANIYE_TRUBY; /* йнл_цсх_бйк_бюйсслхпнбюмхе_рпсаш */
	i = KOM_GUI_VYK_VAKUUMIROVANIYE_TRUBY; /* йнл_цсх_бшй_бюйсслхпнбюмхе_рпсаш */
	i = KOM_GUI_VKL_VAKUUMNUYU_PODSISTYEMU; /* йнл_цсх_бйк_бюйсслмсч_ондяхярелс */
	i = KOM_GUI_VYK_VAKUUMNUYU_PODSISTYEMU; /* йнл_цсх_бшй_бюйсслмсч_ондяхярелс */
	i = KOMANDY_OT_GUI; /* йнлюмдш_нр_цсх */
	i = IZMN_FP_P_VbakyeKompryessora; /* хглм_то_P_бАЮЙЕйНЛОПЕЯЯНПЮ */
	i = IZMN_FP_P_Vpatrubkye; /* хглм_то_P_бОЮРПСАЙЕ */
	i = IZMN_FP_T_Vrubashkye; /* хглм_то_T_бПСАЮЬЙЕ */
	i = IZMN_FP_T_Vbakye; /* хглм_то_T_бАЮЙЕ */
	i = IZMN_FP_P_VtrubyeSidyer; /* хглм_то_P_бРПСАЕяХДЕП */
	i = KOMANDY_IZM_FP; /* йнлюмдш_хгл_то */
	i = PK_GUI_OTKAZ_OTKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_нрйюг_нрйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_OTKAZ_ZAKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_нрйюг_гюйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_OTKAZ_OTKRYTIYA_SAPUNA; /* ой_цсх_нрйюг_нрйпшрхъ_яюосмю */
	i = PK_GUI_OTKAZ_ZAKRYTIYA_SAPUNA; /* ой_цсх_нрйюг_гюйпшрхъ_яюосмю */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_VYENTILYATORA; /* ой_цсх_нрйюг_бйкчвемхъ_бемрхкърнпю */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_VYENTILYATORA; /* ой_цсх_нрйюг_бшйкчвемхъ_бемрхкърнпю */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_USTR_PLAV_PUSKA; /* ой_цсх_нрйюг_бйкчвемхъ_сярп_окюб_осяйю */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_USTR_PLAV_PUSKA; /* ой_цсх_нрйюг_бшйкчвемхъ_сярп_окюб_осяйю */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_RYEGULYATORA_TYEMPYERATURY; /* ой_цсх_нрйюг_бйкчвемхъ_пецскърнпю_релоепюрспш */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_RYEGULYATORA_TYEMPYERATURY; /* ой_цсх_нрйюг_бшйкчвемхъ_пецскърнпю_релоепюрспш */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_RYEGULYATORA_UROVNYA; /* ой_цсх_нрйюг_бйкчвемхъ_пецскърнпю_спнбмъ */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_RYEGULYATORA_UROVNYA; /* ой_цсх_нрйюг_бшйкчвемхъ_пецскърнпю_спнбмъ */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_NASOSA_OKHLAZHDYENIYA; /* ой_цсх_нрйюг_бйкчвемхъ_мюяняю_нукюфдемхъ */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_NASOSA_OKHLAZHDYENIYA; /* ой_цсх_нрйюг_бшйкчвемхъ_мюяняю_нукюфдемхъ */
	i = PK_GUI_IDYET_VAKUUMIROVANIYE_OTKAZ_VYPOLNYENIYA_KOMANDY; /* ой_цсх_хдер_бюйсслхпнбюмхе_нрйюг_бшонкмемхъ_йнлюмдш */
	i = PK_GUI_NYET_USLOVIJ_DLYA_VYPOLNYENIYA_KOMANDY; /* ой_цсх_мер_сякнбхи_дкъ_бшонкмемхъ_йнлюмдш */
	i = PK_GUI_UROVYEN__VODY_V_BAKYE_OKHLAZHDYENIYA_VNYE_NORMY_OTKAZ_VYPOLNYENI; /* ой_цсх_спнбемэ_бндш_б_аюйе_нукюфдемхъ_бме_мнплш_нрйюг_бшонкмемх */
	i = PK_GUI_OTRITSATYEL_NAYA_TYEMPYERATURA_VODY_OTKAZ_VYPOLNYENIYA_KOMANDY; /* ой_цсх_нрпхжюрекэмюъ_релоепюрспю_бндш_нрйюг_бшонкмемхъ_йнлюмдш */
	i = PK_GUI_DAVLYENIYE_V_PATRUBKYE_NYE_UMYEN_SHAYETSYA; /* ой_цсх_дюбкемхе_б_оюрпсайе_ме_слемэьюеряъ */
	i = PK_GUI_DAVLYENIYE_V_VAK_TRUBYE_NYE_UMYEN_SHAYETSYA; /* ой_цсх_дюбкемхе_б_бюй_рпсае_ме_слемэьюеряъ */
	i = PK_GUI_VAKUUMIROVANIYE_USPYESHNO_ZAVYERSHYENO; /* ой_цсх_бюйсслхпнбюмхе_сяоеьмн_гюбепьемн */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_PITANIYA_VAKUUMNOGO_NASOSA; /* ой_цсх_нрйюг_бйкчвемхъ_охрюмхъ_бюйсслмнцн_мюяняю */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_PITANIYA_VAKUUMNOGO_NASOSA; /* ой_цсх_нрйюг_бшйкчвемхъ_охрюмхъ_бюйсслмнцн_мюяняю */
	i = PK_GUI_VYENTILYATOR_VKLYUCHYEN; /* ой_цсх_бемрхкърнп_бйкчвем */
	i = PK_GUI_VYENTILYATOR_VYKLYUCHYEN; /* ой_цсх_бемрхкърнп_бшйкчвем */
	i = PK_GUI_SPONTANNOYE_VYKLYUCHYENIYE_VYENTILYATORA; /* ой_цсх_яонмрюммне_бшйкчвемхе_бемрхкърнпю */
	i = PK_GUI_SPONTANNOYE_VKLYUCHYENIYE_VYENTILYATORA; /* ой_цсх_яонмрюммне_бйкчвемхе_бемрхкърнпю */
	i = PK_GUI_ZATVOR_VAKUUMNYJ_OTKRYT; /* ой_цсх_гюрбнп_бюйсслмши_нрйпшр */
	i = PK_GUI_ZATVOR_VAKUUMNYJ_ZAKRYT; /* ой_цсх_гюрбнп_бюйсслмши_гюйпшр */
	i = PK_GUI_SPONTANNOYE_OTKRYTIYE_ZAT_VAKUUMNOGO; /* ой_цсх_яонмрюммне_нрйпшрхе_гюр_бюйсслмнцн */
	i = PK_GUI_SPONTANNOYE_ZAKRYTIYE_ZAT_VAKUUMNOGO; /* ой_цсх_яонмрюммне_гюйпшрхе_гюр_бюйсслмнцн */
	i = PK_GUI_SAPUN_OTKRYT; /* ой_цсх_яюосм_нрйпшр */
	i = PK_GUI_SAPUN_ZAKRYT; /* ой_цсх_яюосм_гюйпшр */
	i = PK_GUI_SPONTANNOYE_OTKRYTIYE_SAPUNA; /* ой_цсх_яонмрюммне_нрйпшрхе_яюосмю */
	i = PK_GUI_SPONTANNOYE_ZAKRYTIYE_SAPUNA; /* ой_цсх_яонмрюммне_гюйпшрхе_яюосмю */
	i = PK_GUI_PITANIYE_VAKUUMNOGO_NASOSA_VKLYUCHYENO; /* ой_цсх_охрюмхе_бюйсслмнцн_мюяняю_бйкчвемн */
	i = PK_GUI_PITANIYE_VAKUUMNOGO_NASOSA_VYKLYUCHYENO; /* ой_цсх_охрюмхе_бюйсслмнцн_мюяняю_бшйкчвемн */
	i = PK_GUI_SPONTANNOYE_VKLYUCHYENIYE_VAKUUMNOGO_NASOSA; /* ой_цсх_яонмрюммне_бйкчвемхе_бюйсслмнцн_мюяняю */
	i = PK_GUI_SPONTANNOYE_VYKLYUCHYENIYE_VAKUUMNOGO_NASOSA; /* ой_цсх_яонмрюммне_бшйкчвемхе_бюйсслмнцн_мюяняю */
	i = PK_GUI_PITANIYE_RYEGULYATORA_TYEMPYERATURY_VKLYUCHYENO; /* ой_цсх_охрюмхе_пецскърнпю_релоепюрспш_бйкчвемн */
	i = PK_GUI_PITANIYE_RYEGULYATORA_TYEMPYERATURY_VYKLYUCHYENO; /* ой_цсх_охрюмхе_пецскърнпю_релоепюрспш_бшйкчвемн */
	i = PK_GUI_SPONTANNOYE_VKLYUCHYENIYE_RYEGULYATORA_TYEMPYERATURY; /* ой_цсх_яонмрюммне_бйкчвемхе_пецскърнпю_релоепюрспш */
	i = PK_GUI_SPONTANNOYE_VYKLYUCHYENIYE_RYEGULYATORA_TYEMPYERATURY; /* ой_цсх_яонмрюммне_бшйкчвемхе_пецскърнпю_релоепюрспш */
	i = PK_GUI_PITANIYE_RYEGULYATORA_UROVNYA_VKLYUCHYENO; /* ой_цсх_охрюмхе_пецскърнпю_спнбмъ_бйкчвемн */
	i = PK_GUI_PITANIYE_RYEGULYATORA_UROVNYA_VYKLYUCHYENO; /* ой_цсх_охрюмхе_пецскърнпю_спнбмъ_бшйкчвемн */
	i = PK_GUI_SPONTANNOYE_VKLYUCHYENIYE_RYEGULYATORA_UROVNYA; /* ой_цсх_яонмрюммне_бйкчвемхе_пецскърнпю_спнбмъ */
	i = PK_GUI_SPONTANNOYE_VYKLYUCHYENIYE_RYEGULYATORA_UROVNYA; /* ой_цсх_яонмрюммне_бшйкчвемхе_пецскърнпю_спнбмъ */
	i = PK_GUI_PITANIYE_NASOSA_OKHLAZHDYENIYA_VKLYUCHYENO; /* ой_цсх_охрюмхе_мюяняю_нукюфдемхъ_бйкчвемн */
	i = PK_GUI_PITANIYE_NASOSA_OKHLAZHDYENIYA_VYKLYUCHYENO; /* ой_цсх_охрюмхе_мюяняю_нукюфдемхъ_бшйкчвемн */
	i = PK_GUI_SPONTANNOYE_VKLYUCHYENIYE_NASOSA_OKHLAZHDYENIYA; /* ой_цсх_яонмрюммне_бйкчвемхе_мюяняю_нукюфдемхъ */
	i = PK_GUI_SPONTANNOYE_VYKLYUCHYENIYE_NASOSA_OKHLAZHDYENIYA; /* ой_цсх_яонмрюммне_бшйкчвемхе_мюяняю_нукюфдемхъ */
	i = PK_GUI_USTROJSTVO_PLAVNOGO_PUSKA_VKLYUCHYENO; /* ой_цсх_сярпниярбн_окюбмнцн_осяйю_бйкчвемн */
	i = PK_GUI_USTROJSTVO_PLAVNOGO_PUSKA_VYKLYUCHYENO; /* ой_цсх_сярпниярбн_окюбмнцн_осяйю_бшйкчвемн */
	i = PK_GUI_SPONTANNOYE_VKLYUCHYENIYE_USTROJSTVA_PLAVNOGO_PUSKA; /* ой_цсх_яонмрюммне_бйкчвемхе_сярпниярбю_окюбмнцн_осяйю */
	i = PK_GUI_SPONTANNOYE_VYKLYUCHYENIYE_USTROJSTVA_PLAVNOGO_PUSKA; /* ой_цсх_яонмрюммне_бшйкчвемхе_сярпниярбю_окюбмнцн_осяйю */
	i = PK_GUI_OTKAZ_VAKUUMIROVANIYA; /* ой_цсх_нрйюг_бюйсслхпнбюмхъ */
	i = PK_GUI_OTKAZ_VKLYUCHYENIYA_VAKUUMNOJ_PODSISTYEMY; /* ой_цсх_нрйюг_бйкчвемхъ_бюйсслмни_ондяхярелш */
	i = PK_GUI_OTKAZ_VYKLYUCHYENIYA_VAKUUMNOJ_PODSISTYEMY; /* ой_цсх_нрйюг_бшйкчвемхъ_бюйсслмни_ондяхярелш */
	i = PK_GUI_YEST__DOSTOVYERNOST__KONTROLYA_OTKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_еярэ_днярнбепмнярэ_йнмрпнкъ_нрйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_NYET_DOSTOVYERNOSTI_KONTROLYA_OTKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_мер_днярнбепмнярх_йнмрпнкъ_нрйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_YEST__DOSTOVYERNOST__KONTROLYA_ZAKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_еярэ_днярнбепмнярэ_йнмрпнкъ_гюйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_NYET_DOSTOVYERNOSTI_KONTROLYA_ZAKRYTIYA_ZATVORA_VAKUUMNOGO; /* ой_цсх_мер_днярнбепмнярх_йнмрпнкъ_гюйпшрхъ_гюрбнпю_бюйсслмнцн */
	i = PK_GUI_YEST__DOSTOVYERNOST__KONTROLYA_SAPUNA; /* ой_цсх_еярэ_днярнбепмнярэ_йнмрпнкъ_яюосмю */
	i = PK_GUI_NYET_DOSTOVYERNOSTI_KONTROLYA_SAPUNA; /* ой_цсх_мер_днярнбепмнярх_йнмрпнкъ_яюосмю */
	i = PK_GUI_YEST__DOSTOVYERNOST__KONTROLYA_USTR_PLAV_PUSKA; /* ой_цсх_еярэ_днярнбепмнярэ_йнмрпнкъ_сярп_окюб_осяйю */
	i = PK_GUI_NYET_DOSTOVYERNOSTI_KONTROLYA_USTR_PLAV_PUSKA; /* ой_цсх_мер_днярнбепмнярх_йнмрпнкъ_сярп_окюб_осяйю */
	i = PK_GUI_YEST__DOSTOVYERNOST__KONTROLYA_PIT_VAK_NASOSA; /* ой_цсх_еярэ_днярнбепмнярэ_йнмрпнкъ_охр_бюй_мюяняю */
	i = PK_GUI_NYET_DOSTOVYERNOSTI_KONTROLYA_PIT_VAK_NASOSA; /* ой_цсх_мер_днярнбепмнярх_йнмрпнкъ_охр_бюй_мюяняю */
	i = PK_GUI_YEST__DOSTOVYERNOST__KONTROLYA_PIT_VYENTILYATORA; /* ой_цсх_еярэ_днярнбепмнярэ_йнмрпнкъ_охр_бемрхкърнпю */
	i = PK_GUI_NYET_DOSTOVYERNOSTI_KONTROLYA_PIT_VYENTILYATORA; /* ой_цсх_мер_днярнбепмнярх_йнмрпнкъ_охр_бемрхкърнпю */
	i = PK_GUI_FP_P_VbakyeKompryessora; /* ой_цсх_то_P_бАЮЙЕйНЛОПЕЯЯНПЮ */
	i = PK_GUI_FP_P_Vpatrubkye; /* ой_цсх_то_P_бОЮРПСАЙЕ */
	i = PK_GUI_FP_T_Vrubashkye; /* ой_цсх_то_T_бПСАЮЬЙЕ */
	i = PK_GUI_FP_T_Vbakye; /* ой_цсх_то_T_бАЮЙЕ */
	i = PK_GUI_FP_P_VtrubyeSidyer; /* ой_цсх_то_P_бРПСАЕяХДЕП */
	i = IZMN_NP_1; /* хглм_мо_1 */
	i = IZMN_NP_P_VbakyeKompryessora; /* хглм_мо_P_бАЮЙЕйНЛОПЕЯЯНПЮ */
	i = IZMN_NP_Patmosf; /* хглм_мо_PЮРЛНЯТ */
	i = IZMN_NP_GlubokijVakuumTruby; /* хглм_мо_цКСАНЙХИбЮЙССЛрПСАШ */
	i = IZMN_NP_N; /* хглм_мо_N */
	i = PK_GUI_OSHIBKA_KODA_KOMANDY_OT_GUI; /* ой_цсх_ньхайю_йндю_йнлюмдш_нр_цсх */
	fclose(file);
}
